Develop
java-park-mail-ru/42-09-2017 pull request #1
Opened 2017-09-19 09:30 UTC by ArturBmstu

version 0.9

2017-09-19 11:59 UTC, isopov commented
Ну что, начнем-с.

1. maven-compiler-plugin - его конфигурация вам приходит из spring-boot-starter-parent и можно вообще удалить про него из pom.xml
2. Закоментированный код лучше удалить - визуальный мусор, как правило (класс User)
3. UserController.whoAmI - почему называется не me() по урлу? искать потом сложнее, если одно и то же называется разными названиями. почему POST метод?
4. Подтверждение пароля - почему это не делается полностью на frontend?
5. Можно перерегистрировать пользователя заново сколько угодно раз и никаких проверок на "уже существует"?
6. UserService.getUserList() - нигде не используется - этот класс вы будете переписывать - его публичное API стоит держать минимальным
7. Можно зарегистрировать пользователя с пустым паролем, и потом при логине будет падать NPE
8. `consumes = "application/json"` в методе логина - почему здесь есть, а в других местах нигде нет? я попробовал - и без него всё также
9. `@RequestBody` - зачем эта аннотация? в доках на `@RestController` написано, что она подразумевается
10. `@JsonView(View.Summary.class)` на регистрации - там всегда null возвращается, не нужно это.
11. Если я залогинен - можно обновить пароль без указания старого?
12. logout возвращает `ResponseEntity<String>`, хотя мог бы просто `String` 
13. "Константы" в  Java делаеют немного по-другому - вместо `private final String sessionAttr = "user_info";` - `private static final String SESSION_ATTR = "user_info";`
14. Почему userService в контроллере - не финальное поле?
15. UserController.getUser() - какая-то заглушка - удалите
16. ru.mail.park.response.ResponseBody не используется - удалите.

2017-09-19 12:08 UTC, isopov requested changes
В комменте написал замечания.

2017-09-19 12:09 UTC, ArturBmstu commented
понял

2017-09-19 17:18 UTC, ArturBmstu commented
Вы наверное имели ввиду, что `@ResponseBody` подразумевается. Про `@RequestBody` там ничего такого нет

2017-09-19 18:16 UTC, isopov commented
Да нет, имел я в виду `@RequestBody`, но в доке про неё действительно ничего нет... можно оставить (хотя я попоробовал и можно и без неё..)

2017-09-19 21:36 UTC, ArturBmstu commented
а у меня без `@RequestBody` не работает

2017-09-20 16:45 UTC, isopov commented
1. Почему `ResponseEntity<? extends ResponseBody>` а не просто `ResponseEntity<ResponseBody>` ?
2. Почему `ResponseEntity<? extends ResponseBody>` а не просто `ResponseBody`
3. Почему на `ResponseEntity` `@JsonView`?
4. Зачем вообще ResponseEntity - зачем свои коды ошибок/ответов кроме кодов ответов HTTP?
5. Серьёзно? Регулярные выражения для валидации всего чего только можно, с компиляцией их на каждую валидацию? User-friendly серверная валидация с возвращением всех ошибок? Мне кажется это должно быть на клиенте, а сервер можно быстро возвращать первую ошибку, на которую наталкивается.
6. UserService.findUser не испольуется

2017-09-21 12:30 UTC, ArturBmstu commented
наверное стоит вынести сообщения в отдельный класс

2017-09-21 13:08 UTC, ArturBmstu commented
упс, формат ответов хотел другим сделать, сейчас поправлю

2017-09-21 19:08 UTC, ArturBmstu commented
Не могли бы подсказать заодно, что лучше использовать вместо `enum`а для сообщений?

2017-09-22 19:19 UTC, ArturBmstu commented
и еще вы в слаке написали, что спринг можно легко настроить на валидацию приходящих данных. об этом тоже скажите, пожалуйста

2017-09-24 17:51 UTC, isopov commented
1. Чтобы валидировать спрингом просто поставить на аргумент метода контроллера аннотацию `javax.validation.Valid`, а на поля класса аргумента аннотации из серии `javax.validation.constraints.NotNull` - они у вас уже есть в зависимостях и валидатор спрингом уже подключен. Ну а дальше гуглить и читать документацию, если захотите настроить сообщения об ошибках..
2. `Validator` - сделайте его тоже сервисом, а не создавайте на каждый запрос
3. Зачем выносить строки для регулярных выражений в константы, если они используются только один раз?
4. Map с названием `*List` - это шикарно - так быстро протухает код и становится мистическим и непонятным - вам с этим еще много бороться придётся - начинайте прямо сейчас.
5. Вот вместо этого делают копирующие конструкторы:
```
User user = new User(
                userSignupInfo.getUsername(),
                userSignupInfo.getEmail(),
                userSignupInfo.getPassword()
        );
```

2017-09-24 21:54 UTC, ArturBmstu commented
bean validation не очень удобно приспосабливать для фронтендеров. Лучше ли сделать валидацию с помощью исключений? или оставить как есть

2017-09-25 07:13 UTC, isopov commented
@ArturBmstu Можно исключениями - через https://spring.io/blog/2013/11/01/exception-handling-in-spring-mvc - мне кажется, что это будет проще всего и удобнее читать (а это главное в коде). А уж если производительность будет недостаточной, то можно начинать ухудшать код (хотя я бы сначала переделал такое ожидаемое исключение на не собирающее стектрейс, да и потом посмотрел в сторону какого-нибудь java.servlet.Filter-а валидиационного - код чем чище, короче и понятнее - тем лучше.

2017-09-25 08:54 UTC, isopov commented
@ArturBmstu про enum-ы - я бы в этом случае использовал просто строковые константы. enum-ы нужны если передавать их через долгие цепочки вызовы для типобезопасности и если на них вешать таки какое-то поведение - методы в них определять с разным поведением у разных членов enum-а

2017-09-25 08:55 UTC, ArturBmstu commented
хорошо

2017-09-25 13:53 UTC, ArturBmstu commented
мы решили всё-таки отправлять ошибки массивом (c `/signup` и `/update`). Это ж быстрее будет, чем если сервер отдаст сначала одну ошибку в одном field'e, юзер её исправит, отправит запрос и получит снова ответ с ошибкой, но уже в следующем field'e.

2017-09-26 06:24 UTC, isopov commented
@ArturBmstu UserService - а вот его состояние и методы точно не могут быть статическими.

2017-09-26 08:37 UTC, ArturBmstu commented
В связи с чем? Я это сделал чтобы методы валидатора были статическими, не сто́ит?

2017-09-26 16:28 UTC, isopov commented
@ArturBmstu 
Пока это сложно увидеть, но давайте попробую объяснить. Статическим состоянием класса спринг не управляет - оно лежит не в ApplicationContext. Это препятствует рестарту сервиса без рестарта JVM, усложняет управление зависимостями между сервисами - непонятно какой когда уже готов, а еще нет, их сложнее тестировать (следующая лекция).

2017-09-26 16:37 UTC, ArturBmstu commented
отсюда можно сделать вывод что в сервисном классе Валидатор тоже не должно быть статических методов?

2017-09-26 16:45 UTC, isopov commented
@ArturBmstu можно сделать такой вывод. А можно и не делать. Мне, например, кажется странным, что валидатор для валидации лазит в базу. С другой стороны - это по нему сразу же видно, когда он сервис базы берет в конструкторе, так что и пускай лазит.

Ну и вы понимаете же, что ситуация
1. пользователь пошел регистрироваться с логином foobar, валидатор его пропустил
2. второй пользователь пошел регистрироваться с тем же самым логином, валидатор его пропустил
3. первый пользователь успешно зарегистрировался
4. второй пользователь не сумел зарегистрироваться - вылетела ошибка
редкая, но полностью нормальная (кстати, надо тут следить, чтобы регистрация второго пользователя не переписывала регистрацию первого - это было бы явным багом) - впрочем об этом стоит думать, когда мы перейдём на реальную базу и дойдём до многопоточности.

2017-09-27 06:48 UTC, isopov commented
@ArturBmstu мержить можно уже? ))

2017-09-27 08:20 UTC, ArturBmstu commented
Это же на ваше усмотрение. Я лично всё, что хотел, сделал. Ну почти. Ещё хочу Bean Validation всё-таки прикрутить, но это не сразу.

2017-09-27 08:45 UTC, isopov approved these changes

2017-09-27 08:46 UTC, merged