Develop
java-park-mail-ru/42-09-2017 pull request #2
Opened 2017-10-19 16:50 UTC by ArturBmstu

2017-10-23 18:55 UTC, KSolovyev requested changes

2017-10-23 18:55 UTC, KSolovyev commented on .travis.yml
> +#deploy:
уберите закомментированный код

2017-10-23 18:55 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/validators/CValidatorChain.java
> +public class CValidatorChain {
надо заиспользовать spring-boot-starter-validation
https://spring.io/guides/gs/validating-form-input/
Просто в контроллере добавляете аннотацию `@Valid` перед сущностью, которую надо валидировать

можно использовать, как  javax.validators, так и hibernate-validator
Там есть почти все что нужно `@Length`, `@Email` и тд
можно использовать аннотацию `@Validated(<Validator class>)` на классе и подсовывать в нее кастомные валидаторы (Validator, SmartValidator и тд).  
В общем легко получаем все что нужно, не используя name convention

2017-10-23 18:55 UTC, KSolovyev commented on src/main/java/ru/mail/park/AppConfiguration.java
> +        ModelMapper modelMapper = new ModelMapper();
а зачем нужна такая машинерия? Можно же просто было написать что-то вроде `UserHelper.toDTO(User user) {...}`

2017-10-23 18:55 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/UserDao.java
> +@Transactional
`@EnableTransactionManagement` забыли
Надо добавить в `@Configuration`, если хотите использовать такие транзакции

2017-10-24 18:32 UTC, ArturBmstu commented on src/main/java/ru/mail/park/AppConfiguration.java
> +        ModelMapper modelMapper = new ModelMapper();
написать где?

2017-10-26 19:58 UTC, ArturBmstu commented on src/main/java/ru/mail/park/AppConfiguration.java
> +        ModelMapper modelMapper = new ModelMapper();
Понял. Класс со статическим методом

2017-10-26 23:55 UTC, ArturBmstu commented on src/main/java/ru/mail/park/controllers/validators/CValidatorChain.java
> +public class CValidatorChain {
До этого всё так и было. Но проблема появилась в том, что т.к. на каждое поле в классе нужно по несколько Constraint'ов, они валидировались все сразу. А нам нужно чтобы валидация каждого поля останавливалась на первом заваленном Constraint'е.
Почитал документацию на Bean Validation. Есть такая штука, как `@GroupSequence`. В ней можно задать последовательность валидации. Но я посчитал что это дорогое удовольствие, потому что будет большая куча интерфейсов, определяющих группы валидации, и используемых как члены `@GroupSequence`.
Это меня вынудило сделать вот такую вот шарманку с рефлексией

2017-10-27 00:01 UTC, ArturBmstu commented on src/main/java/ru/mail/park/services/UserDao.java
> +@Transactional
Добавил. Но для чего нужна эта аннотация? не нашел толкового объяснения

2017-10-28 16:56 UTC, KSolovyev commented on src/main/java/ru/mail/park/services/UserDao.java
> +@Transactional
Чтобы включились декларативные транзакции. Без этого ваш класс не будет пропатчен и не будет создана специальная прокси, которая управляет транзакциями. Проверьте, она должна светиться в дебаггере при переходе из контроллера в сервис

2017-10-28 16:57 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/validators/CValidatorChain.java
> +public class CValidatorChain {
а зачем останавливаться на первом поле?? Надо отдавать все ошибки, пусть фронт обрабатывает))

2017-10-28 16:58 UTC, KSolovyev commented on src/main/java/ru/mail/park/AppConfiguration.java
> +        ModelMapper modelMapper = new ModelMapper();
ага. Будет гораздо проще

2017-10-28 17:28 UTC, ArturBmstu commented on src/main/java/ru/mail/park/controllers/validators/CValidatorChain.java
> +public class CValidatorChain {
на первом поле никто не останавливается. я имею ввиду, что выводились для каждого из полей избыточные ошибки.
и пока это писал, родилась идея для исправления этого.

2017-10-28 17:28 UTC, ArturBmstu commented on src/main/java/ru/mail/park/controllers/validators/CValidatorChain.java
> +public class CValidatorChain {
т.е. то что есть в данный момент - это не очень хорошо?

2017-10-29 14:16 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/validators/CValidatorChain.java
> +public class CValidatorChain {
то, что есть не очень хорошо, верно.
Отдавайте все, что нашли. Фронт в конце концов может только одну ошибку показывать, если не умеет все

2017-10-31 23:39 UTC, ArturBmstu commented
Почему travis говорит что нет типа jsonb для постгреса?

2017-11-06 16:27 UTC, KSolovyev requested changes

2017-11-06 16:27 UTC, KSolovyev commented on pom.xml
> +            <artifactId>junit</artifactId>
junit есть в starter-test

2017-11-06 16:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/domain/BoardMeta.java
> +public class BoardMeta {
Игровый изменения нужно унести в ветку с 3РК. Здесь их быть не должно

2017-11-06 16:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/domain/dto/UserDto.java
> +    @NotExists(field = "username", message = MessageConstants.EXISTS_USERNAME)
а зачем вы проверяете существование пользователя с помощью валидаторов? 
Тем более это логика создания, и она не имеет отношения к валидности модели

2017-11-06 16:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/validators/CSizeValidator.java
> +public class CSizeValidator implements ConstraintValidator<CSize, CharSequence> {
а чем вам обычный Length не подошел?

2017-11-06 16:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/UserController.java
> +            throw new ControllerValidationException(responseList);
а зачем вы тут исключение кидаете, когда можно нормальный ответ вернуть?

2017-11-06 16:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/validators/CNotBlankValidator.java
> +public class CNotBlankValidator implements ConstraintValidator<CNotBlank, CharSequence> {
аналогичный вопрос, чем вам стандартный валидатор-то не угодил?

2017-11-06 16:27 UTC, KSolovyev commented on src/main/java/ru/mail/park/controllers/validators/LoginDataValidator.java
> +        return user == null || userDao.checkUserPassword(user, password);
это опять не валидация. Это бизнес логика и она должна быть в сервисе

2017-11-06 16:28 UTC, KSolovyev commented
тревис сломался

2017-11-06 16:30 UTC, ArturBmstu commented
в .properties поменял название базы, а в тревисе забыл

2017-11-06 16:32 UTC, ArturBmstu commented on src/main/java/ru/mail/park/controllers/validators/CNotBlankValidator.java
> +public class CNotBlankValidator implements ConstraintValidator<CNotBlank, CharSequence> {
Стандартный валидатор проверяет еще на NotNull. Мне нужно только на пустоту

2017-11-06 16:33 UTC, ArturBmstu commented on src/main/java/ru/mail/park/domain/dto/UserDto.java
> +    @NotExists(field = "username", message = MessageConstants.EXISTS_USERNAME)
ладно, перенесу. думал, так красивее будет

2017-11-06 16:36 UTC, ArturBmstu commented on src/main/java/ru/mail/park/controllers/validators/CSizeValidator.java
> +public class CSizeValidator implements ConstraintValidator<CSize, CharSequence> {
length и size не подошли тем, что мне не нужно выдавать ошибку если строка пустая

2017-11-06 16:36 UTC, ArturBmstu commented on src/main/java/ru/mail/park/domain/BoardMeta.java
> +public class BoardMeta {
хорошо

2017-11-08 19:40 UTC, KSolovyev requested changes

2017-11-08 19:40 UTC, KSolovyev commented on pom.xml
> +        <version>2.0.0.M4</version>
Давайте уж тогда использовать последний 2.0.0.M5

2017-11-09 13:38 UTC, KSolovyev approved these changes

2017-11-09 13:38 UTC, merged

2017-11-09 13:38 UTC, KSolovyev commented
Надо будет помержить master в develop

2017-11-09 13:40 UTC, ArturBmstu commented
А для чего