Rk3
java-park-mail-ru/42-09-2017 pull request #4
Opened 2017-11-30 19:33 UTC by ArturBmstu

**Пулл-реквест для третьего рубежного контроля**

2017-12-13 11:59 UTC, Badya requested changes

2017-12-13 11:59 UTC, Badya commented on src/main/java/ru/mail/park/controllers/GameController.java
> +//@CrossOrigin(origins = {
Комменты убираем

2017-12-13 11:59 UTC, Badya commented on src/main/java/ru/mail/park/controllers/validators/groups/SimulationSnap.java
> +public class SimulationSnap {
Что это?

2017-12-13 11:59 UTC, Badya commented on src/main/java/ru/mail/park/domain/Id.java
> +public class Id<T> {
Зачем Т ?

2017-12-13 11:59 UTC, Badya commented on src/main/java/ru/mail/park/mechanics/GameMechanics.java
> +    public synchronized void tryStartSimulation(Id<User> userId, List<BodyFrame> snap) {
Почему тут synchronized, а больше нигде нету?

2017-12-18 19:53 UTC, ArturBmstu commented on src/main/java/ru/mail/park/domain/Id.java
> +public class Id<T> {
Это дженерик by Konstantin Solovyev. Для облегчения разработки

2017-12-18 19:57 UTC, ArturBmstu commented on src/main/java/ru/mail/park/controllers/validators/groups/SimulationSnap.java
> +public class SimulationSnap {
Это класс, используемый в качестве валидационной группы. В двух разных классах есть поле одного типа. Но в них нужно по-разному валидировать это поле. Для этого и создал его.

2017-12-21 12:48 UTC, merged